### ISSUE TITLE
Error occurred while RSpecRails/InferredSpecType: undefined method `[]' for nil

### ISSUE THREAD

**Issue by aarestad** [rubocop/rubocop-rspec_rails#29]
This error popped up a _bunch_ when we turned on the `rubocop-rspec_rails` plugin. Over 100 errors of the same kind. Typical stack trace:

```
An error occurred while RSpecRails/InferredSpecType cop was inspecting /Users/aarestad/[redacted]/gems/box_plot/spec/box_plot_spec.rb:60:2.[0m
undefined method `[]' for nil
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:88:in `regular'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:82:in `all'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:37:in `example_group?'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-rspec_rails-2.28.3/lib/rubocop/cop/rspec_rails/inferred_spec_type.rb:60:in `on_block'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:107:in `public_send'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:105:in `each'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:69:in `on_block'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-ast-1.31.3/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cop/team.rb:98:in `investigate'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:349:in `block in inspect_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:348:in `each'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:348:in `flat_map'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:348:in `inspect_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:291:in `block in do_inspection_loop'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:325:in `block in iterate_until_no_changes'
<internal:kernel>:187:in `loop'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:318:in `iterate_until_no_changes'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:287:in `do_inspection_loop'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:168:in `block in file_offenses'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:193:in `file_offense_cache'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:167:in `file_offenses'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:158:in `process_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:139:in `block in each_inspected_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:138:in `each'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:138:in `reduce'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:138:in `each_inspected_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:124:in `inspect_files'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/runner.rb:77:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/command/execute_runner.rb:47:in `with_redirect'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/command.rb:11:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli/environment.rb:18:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli.rb:122:in `run_command'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli.rb:129:in `execute_runners'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli.rb:51:in `block in run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli.rb:81:in `profile_if_needed'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/cli.rb:43:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/server_command/exec.rb:22:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/server_command/base.rb:24:in `block in run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/server_command/base.rb:23:in `chdir'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/server_command/base.rb:23:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/socket_reader.rb:33:in `block in read!'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/helper.rb:26:in `redirect'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/socket_reader.rb:28:in `read!'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:86:in `read_socket'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:61:in `block in process_input'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/cache.rb:140:in `write_pid_file'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:60:in `process_input'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:49:in `block in detach_server'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:46:in `fork'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:46:in `detach_server'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/core.rb:38:in `start'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/client_command/start.rb:42:in `block in run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/cache.rb:127:in `acquire_lock'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/client_command/start.rb:29:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/client_command/exec.rb:40:in `ensure_server!'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/server/client_command/exec.rb:19:in `run'
/Users/aarestad/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/exe/rubocop:12:in `<top (required)>'
/Users/aarestad/.rbenv/versions/3.3.1/bin/rubocop:25:in `load'
/Users/aarestad/.rbenv/versions/3.3.1/bin/rubocop:25:in `<main>'
```

Version of Rubocop:
```
1.63.5 (using Parser 3.3.1.0, rubocop-ast 1.31.3, running on ruby 3.3.1) +server [arm64-darwin23]
```

Version of rubocop-rspec_rails: `2.28.3`

**Comment by pirj** [comment]
Mind sharing your .rubocop.yml files?

**Comment by aarestad** [comment]
Can do!
[rubocop-files.tar.gz](https://github.com/rubocop/rubocop-rspec_rails/files/15336129/rubocop-files.tar.gz)

**Comment by pirj** [comment]
Do you have rubocop-rspec in your Gemfile as this [section suggests](https://github.com/rubocop/rubocop-rspec_rails/tree/master?tab=readme-ov-file#installation)?
I apologise for the inconvenience, this is not obvious. We couldn’t do otherwise, as rubygems were complaining about a circular dependency.

**Comment by aarestad** [comment]
Actually yes - we _just_ have rubocop-rspec, and get rspec_rails as a transitive dependency. (I basically discovered this by accident by turning on _just_ rspec_rails instead of rspec, as I probably should have)

**Comment by pirj** [comment]
Please help me understand.

> when we turned on the rubocop-rspec_rails plugin

> we just have rubocop-rspec

but in .rubocop.yml you only have require: rubocop-rspec_rails ?

If you also require rubocop-rspec from .rubocop.yml, the problem goes away?

**Comment by aarestad** [comment]
Yes, that's correct! When I add `rubocop-rspec` as well, it seems to be fine. We would probably prefer to have just `rubocop-rspec` anyway in our config.

**Comment by pirj** [comment]
Nice!

My apologies for the confusion again. We plan to release major versions soon and untangle the two gems.

**Comment by aarestad** [comment]
No worries at all - thank you for these awesome tools :)
